name: Github Actions

# 모든 브랜치에서 push 이벤트가 일어났을 때 실행
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
		  # 소스를 가져오기
      - name: Checkout
        uses: actions/checkout@v2

			# DockerHub에 업로드할 저장소 설정
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: leophenomx/github-action # 여기에 DockerHub 저장소 입력
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
			
			# S3 버킷에서 더미 파일 Download
      - name: Download S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \    # 여기에 S3 버킷 주소입력
            s3://github.access.test/test-img.png ./

			# Docker Container 안에서 접근할 수 있는지 확인
      - name : Check Path
        run: |
          ls -al ./ && \
          md5sum ./test-img.png

			# Docker Hub에 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

			# DockerHub에 image를 build하고 push
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
	        file: ./Dockerfile    # Dockerfile은 프로젝트 루트 디렉토리에 존재해야함
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}